name: Build and Run Container with PR Number

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: "1. checkout"
      uses: actions/checkout@v4

    - name: "2. enable docker buildx"
      uses: docker/setup-buildx-action@v3
    
    - name: "3. login ghcr.io"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: "4. generate metadata"
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.actor }}/ghcr-container-push-demo
        tags: |
          type=raw,value=latest
          type=sha,prefix=,suffix=,format=short
    
    - name: "5. build container image, and push"
      uses: docker/build-push-action@v5
      with:
        file: ./docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/ghcr-container-push-demo:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/ghcr-container-push-demo:buildcache,mode=max

    - name: "6. run gitDiffCheck.py with PR number"
      run: |
         docker run --rm \
           -e GITHUB_TOKEN=${{ secrets.CR_PAT }} \
           -e AACS=${{ secrets.AACS }} \
           -e AACSAPIkey=${{ secrets.AACSAPIKEY }} \
           -e HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
           -v ${{ github.workspace }}:/app \
           -w /app \
           ghcr.io/${{ github.actor }}/ghcr-container-push-demo:latest \
           bash -c "git config --global --add safe.directory /app && python3 gitDiffCheck.py ${{ github.event.pull_request.number }}"
